# Generated by Django 3.1 on 2020-12-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('FeMale', 'FeMale')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
